spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  jmx:
    default-domain: test
